import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
} from "constants/navigation.constant";

import { DOCS_PREFIX_PATH } from "constants/route.constant";
import { ADMIN, USER } from "constants/roles.constant";
import docNavigationConfig from "./doc.navigation.config";

const navigationConfig = [
  // Offchain
  {
    key: "OffChain",
    path: "",
    title: "Collapse Menu",
    translateKey: "nav.OffChain.OffChain",
    icon: "home",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "OffChain.item1",
        path: "/nft-sales",
        title: "Collapse menu item 1",
        translateKey: "nav.OffChain.item1",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "OffChain.item2",
        path: "/nft-minters",
        title: "Collapse menu item 2",
        translateKey: "nav.OffChain.item2",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "OffChain.item3",
        path: "/nft-royalty",
        title: "Collapse menu item 3 ",
        translateKey: "nav.OffChain.item3",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "OffChain.item4",
        path: "/nft-collection",
        title: "Collapse menu item 4 ",
        translateKey: "nav.OffChain.item4",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "OffChain.item5",
        path: "/nft-collection-owners",
        title: "Collapse menu item 5 ",
        translateKey: "nav.OffChain.item5",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "OffChain.item6",
        path: "/creditcard-transactions",
        title: "Collapse menu item 6 ",
        translateKey: "nav.OffChain.item6",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  // {
  //   key: "home",
  //   path: "/home",
  //   title: "Home ",
  //   translateKey: "nav.home",
  //   icon: "home",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  /** Example purpose only */
  {
    key: "singleMenuItem",
    path: "/whitelist-blacklist",
    title: "Whitelist Contract",
    translateKey: "nav.singleMenuItem",
    icon: "singleMenu",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: "collapseMenu",
    path: "",
    title: "Collapse Menu",
    translateKey: "nav.collapseMenu.collapseMenu",
    icon: "collapseMenu",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "collapseMenu.item2",
        path: "/normal-transaction",
        title: "Collapse menu item 2",
        translateKey: "nav.collapseMenu.item2",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "collapseMenu.item3",
        path: "/internal-transaction",
        title: "Collapse menu item 3",
        translateKey: "nav.collapseMenu.item3",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "collapseMenu.item1",
        path: "/erc20",
        title: "Collapse menu item 1 ",
        translateKey: "nav.collapseMenu.item1",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "collapseMenu.item4",
        path: "/erc721",
        title: "Collapse menu item 4",
        translateKey: "nav.collapseMenu.item4",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },

  ...docNavigationConfig,

  // {
  //   key: "groupMenu",
  //   path: "",
  //   title: "Group Menu",
  //   translateKey: "nav.groupMenu.groupMenu",
  //   icon: "",
  //   type: NAV_ITEM_TYPE_TITLE,
  //   authority: [],
  //   subMenu: [
  //     {
  //       key: "groupMenu.single",
  //       path: "/group-single-menu-item-view",
  //       title: "Group  Whitelist Contract",
  //       translateKey: "nav.groupMenu.single",
  //       icon: "groupSingleMenu",
  //       type: NAV_ITEM_TYPE_ITEM,
  //       authority: [],
  //       subMenu: [],
  //     },
  //     {
  //       key: "groupMenu.collapse",
  //       path: "",
  //       title: "Group collapse menu",
  //       translateKey: "nav.groupMenu.collapse.collapse",
  //       icon: "groupCollapseMenu",
  //       type: NAV_ITEM_TYPE_COLLAPSE,
  //       authority: [],
  //       subMenu: [
  //         {
  //           key: "groupMenu.collapse.item1",
  //           path: "/group-collapse-menu-item-view-1",
  //           title: "Menu item 1",
  //           translateKey: "nav.groupMenu.collapse.item1",
  //           icon: "",
  //           type: NAV_ITEM_TYPE_ITEM,
  //           authority: [],
  //           subMenu: [],
  //         },
  //         {
  //           key: "groupMenu.collapse.item2",
  //           path: "/group-collapse-menu-item-view-2",
  //           title: "Menu item 2",
  //           translateKey: "nav.groupMenu.collapse.item2",
  //           icon: "",
  //           type: NAV_ITEM_TYPE_ITEM,
  //           authority: [],
  //           subMenu: [],
  //         },
  //       ],
  //     },
  //   ],
  // },
];

export default navigationConfig;
